language: python
python:
  - 3.4
env:
  - TOXENV=py34
install:
  - pip install -r requirements-test.txt
  - pip install coveralls
script:
  - py.test md_changelog/tests
after_script:
  coverage run -m py.test
  coverage report
  coveralls;
