language: python
cache: pip
python:
  - 3.4
env:
  - TOXENV=py34
install:
  - pip install --quiet -r requirements-test.txt
  - pip install --quiet tox coveralls

script:
  - tox -r

after_success:
  - coverage run -m py.test tests
  - coverage report
  - coveralls
