language: python
python:
  - 3.4
env:
  - TOXENV=py34
install:
  - pip install --quiet -r requirements-test.txt
  - pip install --quiet coveralls

script:
  - tox

after_success:
  coverage run -m py.test tests
  coverage report
  coveralls
