language: python

python:
  - 3.4

install:
  - pip install --quiet -r requirements-test.txt
  - pip install --quiet coveralls

script:
  - py.test md_changelog/tests

after_script:
  coverage run -m py.test
  coverage report

after_success:
  coveralls
