language: python
python:
  - 3.4
env:
  - TOXENV=py34
before_install:
  - pip install pytest-cov
install:
  - pip install -r requirements-test.txt
  - pip install tox coveralls
script:
  - tox -r
after_success:
  coveralls
